### ISSUE TITLE
dolphin-dev@5.0-11396: hash check failed

### ISSUE THREAD

**Issue by beatbrot** [hermanjustnu/scoop-emulators#13] opened 2019-12-23 10:54 UTC
Checking hash of dolphin-master-5.0-11396-x64.7z ... ERROR Hash check failed!
App:         emulators/dolphin-dev
URL:         https://dl.dolphin-emu.org/builds/dolphin-master-5.0-11396-x64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    341c81803da8bbeb75458e2e38a7c5340eb49bf3af2b31fc02d7d197271fc5fd
Actual:      d77be78ec433c33a1f2e3669a90f02508b74954b2c436dcd661332716e6a9fc0

**Comment by borger** [comment] 2019-12-28 20:01
The issue is fixed on https://github.com/hermanjustnu/scoop-emulators/pull/14

**Closed** 2019-12-29 11:00 UTC
