### ISSUE TITLE
dolphin-dev update 404 error

### ISSUE THREAD

**Issue by DessertArbiter** [hermanjustnu/scoop-emulators#12] opened 2019-12-22 19:39 UTC
```
Updating 'dolphin-dev' (5.0-11393 -> 5.0-11396)
Downloading new version
The remote server returned an error: (404) Not Found.
At D:\Users\tim\Scoop\apps\scoop\current\lib\install.ps1:130 char:9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found.
```

**Comment by borger** [comment] 2019-12-28 20:01
The issue is fixed on https://github.com/hermanjustnu/scoop-emulators/pull/14

**Closed** 2019-12-29 10:59 UTC
